    const Map<int, String> weekdayName = {
      1: "Monday",
      2: "Tuesday",
      3: "Wednesday",
      4: "Thursday",
      5: "Friday",
      6: "Saturday",
      7: "Sunday"
    };
    const Map<int, int> colorsForDay = {
      1: 0xff28E0AE,
      2: 0xffFF0090,
      3: 0xffFFAE00,
      4: 0xff0090FF,
      5: 0xffDC0000,
      6: 0xff0051FF,
      7: 0xff5D50FE
    };

    const Map<int, String> weatherode = {
      0: "Clear sky",
      1: "Mainly clear",
      2: "Partly cloudy",
      3: "Overcast",
      45: "Fog",
      48: "Depositing rime fog",
      51: "Light intensity drizzle",
      53: "Moderate intensity drizzle",
      55: "Dense intensity drizzle",
      56: "Freezing Drizzle",
      57: "Dense intensity Freezing Drizzle",
      61: "Slight intensity Rain",
      63: "Moderate intensity Rain",
      65: "Heavy intensity Rain",
      66: "Light intensity Freezing Rain",
      67: "Heavy intensity Freezing Rain",
      71: "Slight intensity Snow fall",
      73: "Moderate intensity Snow fall",
      75: "Heavy intensity Snow fall",
      77: "Snow grains",
      80: "Slight Rain showers",
      81: "Moderate Rain showers",
      82: "Violent Rain showers",
      85: "Slight snow showers",
      86: "Heavey snow showers",
    };

    const Map<int, String> imagePerWeathercode = {
      0: "sunny.png",
      1: "sunny.png",
      2: "partly-cloudy.png",
      3: "overcast.png",
      45: "fog.png",
      48: "fog.png",
      51: "drizzle.png",
      53: "drizzle.png",
      55: "drizzle.png",
      56: "drizzle.png",
      57: "drizzle.png",
      61: "rain.png",
      63: "rain.png",
      65: "heavy-rain.png",
      66: "rain.png",
      67: "rain.png",
      71: "snow.png",
      73: "snow.png",
      75: "snow.png",
      77: "snow.png",
      80: "rain.png",
      81: "rain.png",
      82: "heavy-rain.png",
      85: "snow.png",
      86: "snow.png",
    };
